import type {
  BEP,
  Role, Member, Team, Phase, Milestone, LBSNode,
  Discipline, Extension, AssetType, Software,
  Objective, BIMUse, Action, FlowEvent, FlowEffect, FlowAutomation, Workflow, Guide, Annex, Standard,
  LOD, LOI, LOIN, Deliverable, Note, EnvVar,
} from '../types/schema.js'
import type { SectionDiff, BepDiff } from '../types/history.js'

export type { SectionDiff, BepDiff }

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Typed entry builder — casts getId/getLabel to (unknown) => string internally. */
function def<T>(
  key: keyof BEP,
  getId: (item: T) => string,
  getLabel: (item: T) => string,
): { key: keyof BEP; getId: (i: unknown) => string; getLabel: (i: unknown) => string } {
  return { key, getId: i => getId(i as T), getLabel: i => getLabel(i as T) }
}

// ─── Array entity definitions ─────────────────────────────────────────────────
//
// One entry per BEP array. Excludes 'flags': generated by the LLM automatically,
// not user-authored plan changes, so they must not trigger pending-changes badges.

export const arrayDefs = [
  def<Role>          ('roles',           i => i.id,    i => i.name),
  def<Member>        ('members',         i => i.email,  i => `${i.name} (${i.email})`),
  def<Team>          ('teams',           i => i.id,     i => `${i.id} — ${i.name}`),
  def<Phase>         ('phases',          i => i.id,     i => i.name),
  def<Milestone>     ('milestones',      i => i.id,     i => i.name),
  def<LBSNode>       ('lbs',             i => i.id,     i => `${i.id} — ${i.name} (${i.type})`),
  def<Discipline>    ('disciplines',     i => i.id,     i => `${i.id} — ${i.name}`),
  def<Extension>     ('extensions',      i => i.id,     i => i.id),
  def<AssetType>     ('assetTypes',       i => i.id,     i => `${i.id} — ${i.name}`),
  def<Software>      ('softwares',       i => i.id,     i => i.name),
  def<Objective>     ('objectives',      i => i.id,     i => i.description),
  def<BIMUse>        ('bimUses',         i => i.id,     i => i.name),
  def<Action>        ('actions',         i => i.id,     i => i.name),
  def<FlowEvent>      ('events',          i => i.id,     i => i.name),
  def<FlowEffect>     ('effects',         i => i.id,     i => i.name),
  def<FlowAutomation> ('automations',     i => i.id,     i => i.name),
  def<Workflow>      ('workflows',       i => i.id,     i => i.name),
  def<Guide>         ('guides',          i => i.id,     i => i.name),
  def<Annex>         ('annexes',         i => i.id,     i => i.name),
  def<Standard>      ('standards',       i => i.id,     i => i.name),
  def<LOD>           ('lods',            i => String(i.id), i => `${i.id} — ${i.name}`),
  def<LOI>           ('lois',            i => String(i.id), i => `${i.id} — ${i.name}`),
  def<LOIN>          ('loin',            i => i.id,     i => i.element),
  def<Deliverable>   ('deliverables',    i => i.id,     i => i.description ?? i.id),
  def<Note>          ('notes',           i => i.id,     i => i.message),
  def<EnvVar>        ('env',             i => i.key,    i => i.key),
]

// ─── Core diff functions ──────────────────────────────────────────────────────

/** Pure: compares two entity arrays and returns what was added, removed, or modified. */
export function diffEntities<T>(
  baseArr: T[],
  currArr: T[],
  getId: (item: T) => string,
  getLabel: (item: T) => string,
): SectionDiff {
  const baseMap = new Map(baseArr.map(i => [getId(i), i]))
  const currMap = new Map(currArr.map(i => [getId(i), i]))
  return {
    added:    currArr.filter(i => !baseMap.has(getId(i))).map(getLabel),
    removed:  baseArr.filter(i => !currMap.has(getId(i))).map(getLabel),
    modified: currArr
      .filter(i => {
        const b = baseMap.get(getId(i))
        return b !== undefined && JSON.stringify(b) !== JSON.stringify(i)
      })
      .map(getLabel),
  }
}

/**
 * Pure: compares two BEP states (current vs base) and returns a structured diff.
 * Standards .md content changes are not detected here — they require zip access
 * and will be handled by the Standards entity when implemented.
 */
export function diffBep(current: BEP, base: BEP): BepDiff {
  // Project object
  let project: BepDiff['project'] = null
  if (JSON.stringify(current.project) !== JSON.stringify(base.project)) {
    const fields = Object.keys({ ...current.project, ...base.project }).filter(k => {
      const a = (current.project as unknown as Record<string, unknown>)[k]
      const b = (base.project as unknown as Record<string, unknown>)[k]
      return JSON.stringify(a) !== JSON.stringify(b)
    })
    project = { changed: true, fields }
  }

  // Entity arrays
  const sections: Record<string, SectionDiff> = {}
  for (const { key, getId, getLabel } of arrayDefs) {
    const baseArr = (base[key] as unknown[]) ?? []
    const currArr = (current[key] as unknown[]) ?? []
    const diff = diffEntities(baseArr, currArr, getId, getLabel)
    if (diff.added.length || diff.removed.length || diff.modified.length)
      sections[key] = diff
  }

  const changedKeys = [...(project ? ['project'] : []), ...Object.keys(sections)]
  return { project, sections, changedKeys }
}
