// part of: node --experimental-strip-types examples/run-all.ts  (use --10 to stop here)
//
// Covers: flags, memory, skill.
//
// These three entities are the LLM's layer of the BEP — they are written by
// the agent, not by the BIM Manager directly.
//
// Flags    — observations generated after analyze_bep. Each flag points to an
//            entity (or to the whole BEP) and carries a severity level. Flags
//            are transient: they are cleared and regenerated on each analysis.
//
// Memory   — a single markdown string the LLM writes to persist context across
//            sessions: confirmed decisions, acknowledged flags, client constraints.
//            The caller owns the full string — there is no append API.
//
// Skill    — instructions authored by the BIM Manager that tell the LLM how to
//            behave in this specific BEP (terminology, tone, LOD conventions).
//            Skill can be copied from a template BEP to seed a new project.

import { readFileSync, writeFileSync } from 'node:fs'
import { Bep } from '../dist/index.js'

const bep = await Bep.open(readFileSync('examples/example.bep'))

const d1 = bep.deliverables.list().find(d => d.description === 'Architectural Model — Floor 1')!.id

// ─── Flags ────────────────────────────────────────────────────────────────────

// Flags point to specific entities (or to the whole BEP when entityId is null)
// and communicate issues the LLM detected during analysis. Once a flag is
// knowingly accepted, it should be removed and the decision documented in memory
// so it is not re-reported in a future session.

console.log('=== flags ===')

// Flags are generated by the LLM after analyze_bep — not authored by users.
// entity / entityId point to what the flag refers to; null means the whole BEP.
const flagsAdded = bep.flags.add([
  {
    entity:      'deliverables',
    entityId:    d1,
    severity:    'warning',
    message:     'Deliverable has no dueDate and the milestone date is in the past.',
    generatedAt: '2026-03-24T08:00:00Z',
  },
  {
    entity:      null,
    entityId:    null,
    severity:    'info',
    message:     'BEP has no KPIs defined in the indicators section.',
    generatedAt: '2026-03-24T08:00:00Z',
  },
])
const f1Id = flagsAdded.succeeded[0].id
const f2Id = flagsAdded.succeeded[1].id
console.log('flags added:', flagsAdded.succeeded.map(f => `[${f.severity}] ${f.message.slice(0, 40)}`))

// remove a flag once it has been resolved or knowingly accepted
const flagRemoved = bep.flags.remove([f2Id, 'ghost-flag'])
console.log('remove info flag:', flagRemoved.succeeded)
console.log('remove ghost (failed):', flagRemoved.failed)
console.log('flags remaining:', bep.flags.list().length)

// ─── Memory ───────────────────────────────────────────────────────────────────

console.log('\n=== memory ===')

// memory is project-specific context the LLM writes for itself to recall across sessions
console.log('memory (empty):', JSON.stringify(await bep.memory.get()))

bep.memory.set([
  '# Project Memory',
  '',
  '- LOD 300 confirmed with client on 2026-03-15.',
  '- Structure team is responsible for all EST deliverables.',
  '- "No KPIs" flag acknowledged — no KPI framework planned for this phase.',
].join('\n'))

console.log('memory set (first 60 chars):', (await bep.memory.get()).slice(0, 60))

// overwrite — no append, the caller owns the full string
const current = await bep.memory.get()
bep.memory.set(current + '\n- Coordination meetings every Monday at 09:00.')
console.log('memory length after update:', (await bep.memory.get()).length)

// ─── Skill ────────────────────────────────────────────────────────────────────

console.log('\n=== skill ===')

// skill is the BIM Manager's instructions for how the LLM should behave in this BEP
console.log('skill (empty):', JSON.stringify(await bep.skill.get()))

bep.skill.set([
  'Always use ISO 19650 terminology.',
  'Prefer concise descriptions — one sentence per deliverable.',
  'When suggesting LOD levels, reference the project phases in bep.phases.',
].join('\n'))

console.log('skill set (first 60 chars):', (await bep.skill.get()).slice(0, 60))

// key use case: copy skill from a template BEP to a new project
const templateBep = Bep.create({ name: 'New Project', code: 'NEW' })
templateBep.skill.set(await bep.skill.get())
console.log('\nskill copied to new BEP (first 50):', (await templateBep.skill.get()).slice(0, 50))

// ─── Save ─────────────────────────────────────────────────────────────────────

writeFileSync('examples/example.bep', await bep.save())
console.log('\nSaved → examples/example.bep')
