// Generated by bep.generateRuntimeTypes() — do not edit manually

// ─── Effects ──────────────────────────────────────────────────────────────────

export interface BepEffects {
  /** Sends a notification to the assigned reviewer when a model is submitted. Uses the comment from the submit event payload. */
  'notify-reviewer': (payload: { comment?: string }) => void
}

// ─── Automations ─────────────────────────────────────────────────────────────

export interface BepAutomations {
  /** Automatically approves the model if no blocking issues are found in the previous review cycle. */
  'auto-approve': (payload: { threshold: number }) => { eventId: string; result: string }
}

// ─── Resolvers ────────────────────────────────────────────────────────────────

export interface BepResolvers {
  /** Fetches a JSON array from the remote data URL. Authenticates with an API key via Authorization header. Returns the raw parsed array. */
  'fetch-json': (url: string, env: { API_KEY: string }) => unknown
}

// ─── Env ──────────────────────────────────────────────────────────────────────

export interface BepEnv {
  /** Bearer token for the project management API. Obtain it from the API settings page of the platform. */
  API_KEY: string
}

// ─── Combined ─────────────────────────────────────────────────────────────────

export interface BepTypes {
  effects:     BepEffects
  automations: BepAutomations
  resolvers:   BepResolvers
  env:         BepEnv
}
