// Generated by bep.generateTypes() — do not edit manually

// ─── ID literals ──────────────────────────────────────────────────────────────

export type ResolverId   = 'fetch-json'
export type AdapterId    = 'pick-label-value'
export type EffectId     = 'notify-reviewer'
export type AutomationId = 'auto-approve'

// ─── Effect payloads ──────────────────────────────────────────────────────────

export interface BepEffectPayloads {
  'notify-reviewer': {
    comment?: string
  }
}

// ─── Automation payloads ──────────────────────────────────────────────────────

export interface BepAutomationPayloads {
  'auto-approve': Record<string, never>
}

// ─── Combined ─────────────────────────────────────────────────────────────────

export interface BepTypes {
  effects:     BepEffectPayloads
  automations: BepAutomationPayloads
  resolvers:   Record<ResolverId, never>
  adapters:    Record<AdapterId, never>
}
